name: BestPractices
configFiles:
  Debug: Configurations/Debug.xcconfig
  Release: Configurations/Release.xcconfig
options:
  bundleIdPrefix: com.westinnewell
  deploymentTarget:
    iOS: "12.0"
targets:
  BestPractices:
    type: application
    platform: iOS
    sources: BestPractices
    dependencies:
      - target: Core
    configFiles:
      Debug: Configurations/BestPracticesDebug.xcconfig
      Release: Configurations/BestPracticesRelease.xcconfig
    scheme:
      testTargets:
        - BestPracticesTests
      gatherCoverageData: true
    prebuildScripts:
      - path: Scripts/swiftlint-check.sh
        name: Swift Lint Check
  BestPracticesTests:
    platform: iOS
    type: bundle.unit-test
    configFiles:
      Debug: Configurations/BestPracticesTests.xcconfig
      Release: Configurations/BestPracticesTests.xcconfig
    settings:
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/BestPractices.app/BestPractices
    sources: Tests/BestPracticesTests/
    dependencies:
      - target: BestPractices
      - framework: Carthage/Build/iOS/Static/Quick.framework
      - framework: Carthage/Build/iOS/Static/Nimble.framework
  Core:
    type: framework
    platform: iOS
    sources:
      - Core
    dependencies:
      - framework: Carthage/Build/iOS/Static/ReactiveCocoa.framework
      - framework: Carthage/Build/iOS/Static/ReactiveSwift.framework
      - framework: Carthage/Build/iOS/Static/Result.framework
    configFiles:
      Debug: Configurations/CoreDebug.xcconfig
      Release: Configurations/CoreRelease.xcconfig
    scheme:
      testTargets: 
        - CoreTests
      gatherCoverageData: true
    prebuildScripts:
      - path: Scripts/swiftlint-check.sh
        name: Swift Lint Check
  CoreTests:
    platform: iOS
    type: bundle.unit-test
    configFiles:
      Debug: Configurations/CoreTests.xcconfig
      Release: Configurations/CoreTests.xcconfig
    sources: Tests/CoreTests/
    dependencies:
      - target: Core
      - framework: Carthage/Build/iOS/Static/Quick.framework
      - framework: Carthage/Build/iOS/Static/Nimble.framework
