name: BestPractices
# In a production application the Team ID would be set here.
# settings:
#  DEVELOPMENT_TEAM: "XXX"
options:
  bundleIdPrefix: com.bestpractices
  deploymentTarget:
    iOS: "12.0"
  createIntermediateGroups: true
settings:
  # These values are read in the appropriate Info.plist files.
  BEST_PRACTICES_VERSION: "0.1.0"
  BEST_PRACTICES_BUILD_NUMBER: 42 # This should automatically be incremented by CI when generating a build
include:
  - Core/project.yml
  - ReactiveExtensions/project.yml
  - Presentations/project.yml
  - BestPractices/project.yml
