name: BestPractices
# In a production application the Team ID would be set here.
# settings:
#  DEVELOPMENT_TEAM: "XXX"
options:
  bundleIdPrefix: com.bestpractices
  deploymentTarget:
    iOS: "12.0"
settings:
  # These values are read in the appropriate Info.plist files.
  BEST_PRACTICES_VERSION: "0.1.0"
  BEST_PRACTICES_BUILD_NUMBER: 42 # This should automatically be incremented by CI when generating a build
targets:
  BestPractices:
    type: application
    platform: iOS
    sources: BestPractices/BestPractices
    dependencies:
      - target: Core
      - carthage: ReactiveCocoa
      - carthage: ReactiveSwift
      - carthage: Result
      - carthage: SnapKit
    scheme:
      testTargets:
        - BestPracticesTests
      gatherCoverageData: true
    prebuildScripts:
      - path: Scripts/swiftlint-check.sh
        name: Swift Lint Check
  BestPracticesTests:
    platform: iOS
    type: bundle.unit-test
    settings:
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/BestPractices.app/BestPractices"
    sources: 
      - BestPractices/BestPracticesTests
      - Shared/SharedTests
    dependencies:
      - target: BestPractices
      - carthage: Quick
      - carthage: Nimble
  Core:
    type: framework
    platform: iOS
    sources: Core/Core
    dependencies:
      - carthage: ReactiveSwift
      - carthage: Result
    scheme:
      testTargets: 
        - CoreTests
      gatherCoverageData: true
    prebuildScripts:
      - path: Scripts/swiftlint-check.sh
        name: Swift Lint Check
  CoreTests:
    platform: iOS
    type: bundle.unit-test
    sources: 
      - Core/CoreTests
      - Shared/SharedTests
    dependencies:
      - target: Core
      - carthage: Quick
      - carthage: Nimble
    settings:
      LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/Frameworks @loader_path/Frameworks $(FRAMEWORK_SEARCH_PATHS)
