include:
  - ../Shared/Project.yml
name: BestPractices
# In a production application the Team ID would be set here.
# settings:
#  DEVELOPMENT_TEAM: "XXX"
settings:
  # These values are read in the appropriate Info.plist files.
  BEST_PRACTICES_VERSION: "0.1.0"
  BEST_PRACTICES_BUILD_NUMBER: 42 # This should automatically be incremented by CI when generating a build
targets:
  BestPractices:
    type: application
    platform: iOS
    sources: 
      - Source
      - Supporting Files
    dependencies:
      - carthage: Core
      - carthage: ReactiveExtensions
      - carthage: Presentations
      - carthage: ReactiveCocoa
      - carthage: ReactiveSwift
      - carthage: Result
      - carthage: SnapKit
    scheme:
      testTargets:
        - BestPracticesTests
      gatherCoverageData: true
    prebuildScripts:
      - path: Scripts/swiftlint-check.sh
        name: Swift Lint Check
  BestPracticesTests:
    platform: iOS
    type: bundle.unit-test
    settings:
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/BestPractices.app/BestPractices"
    sources: 
      - Tests
      - ../Presentations/Tests/Stubs
    dependencies:
      - target: BestPractices
      - carthage: Quick
      - carthage: Nimble
